[workspace]
authors = ["tommasobbb <tommaso.baroni@mail.polimi.it>"]
channels = ["conda-forge"]
name = "xGoals_model"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.1,<3"
pyyaml = ">=6.0.2,<7"
pyarrow = ">=21.0.0,<22"
scikit-learn = ">=1.7.1,<2"
debugpy = ">=1.8.16,<2"
xgboost = ">=3.0.5,<4"
matplotlib = ">=3.10.6,<4"
